In [100]:
import numpy as np
import math

In [21]:
softmax_outputs = [[0.7, 0.1, 0.2], [0.1, 0.5, 0.4], [0.02, 0.9, 0.08]]
softmax_outputs_np = np.array([[0.7, 0.1, 0.2], [0.1, 0.5, 0.4], [0.02, 0.9, 0.08]])
class_targets = [0, 1, 1]
check = [2,2,2]

In [8]:
for targ_idx, distribution in zip(class_targets, softmax_outputs):
#    print(distribution[targ_idx])
    print(distribution)
    print(targ_idx)
    print('-------')


[0.7, 0.1, 0.2]
0
-------
[0.1, 0.5, 0.4]
1
-------
[0.02, 0.9, 0.08]
1
-------


In [30]:
print(softmax_outputs_np[[0, 1, 2], check])

[0.2  0.4  0.08]


In [31]:
type(softmax_outputs)

list

In [32]:
type(softmax_outputs_np)

numpy.ndarray

In [34]:
print(softmax_outputs_np[range(len(softmax_outputs)), class_targets])

[0.7 0.5 0.9]


In [37]:
print(-np.log(softmax_outputs_np[range(len(softmax_outputs)), class_targets]))

[0.35667494 0.69314718 0.10536052]


In [39]:
neg_log = -np.log(softmax_outputs_np[range(len(softmax_outputs)), class_targets])
print(neg_log)
average_loss = np.mean(neg_log)
print(average_loss)

[0.35667494 0.69314718 0.10536052]
0.38506088005216804


## Loss function example

Question: why do we multiply the 'target' vector with softmax_outputs, instead of e.g. computing max of output vectors and evaluating them?
in our case the average loss does not change if values of softmax_outputs are adjusted.

In [85]:
softmax_outputs = np.array([[0.7, 0.1, 0.2], [0.1, 0.5, 0.4], [0.02, 0.9, 0.08]])
class_targets = np.array([[1, 0, 0], [0, 1, 0], [0, 1, 0]])

In [86]:
# Probabilities for target values -
# only if categorical labels
if len(class_targets.shape) == 1:
    correct_confidences = softmax_outputs[range(len(softmax_outputs)), class_targets]
    # Mask values - only for one-hot encoded labels
elif len(class_targets.shape) == 2:
    correct_confidences = np.sum(softmax_outputs*class_targets, axis=1)

In [87]:
neg_log = -np.log(correct_confidences)
average_loss = np.mean(neg_log)
print(average_loss)

0.38506088005216804


## Some checks

In [46]:
class_targets.shape

(3, 3)

In [79]:
np.sum(softmax_outputs*class_targets, axis=1)

array([0.7, 0.5, 0.9])

In [72]:
# np.sum([[0, 2], [1, 5]], axis=1)

In [78]:
# np.amax(softmax_outputs*class_targets, axis = 1)

In [96]:
2.71 ** -10
#1 / 2.71 

4.680659955190793e-05

In [104]:
np.e **(-np.inf)

0.0

## Value clipping

In [118]:
y_pred = np.array([0,0.1,0.2,0.7])

In [123]:
y_pred_clipped = np.clip(y_pred, 0.001, 0.99)

In [124]:
y_pred_clipped

array([0.001, 0.1  , 0.2  , 0.7  ])